# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('street', models.TextField(help_text='IE: 203 56th Street')),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField(help_text='IE: 555-555-5555')),
            ],
        ),
    ]
